
# erpm (electrical rpm) = speed_to_erpm_gain * speed (meters / second) + speed_to_erpm_offset
speed_to_erpm_gain: 4000
speed_to_erpm_offset: 0.0

# Set gains for converting acceleration to current and brake control values
accel_to_current_gain: 100
accel_to_brake_gain: -80

tachometer_ticks_to_meters_gain: 0.00225
# servo smoother - limits rotation speed and smooths anything above limit
max_servo_speed: 3.2 # radians/second
servo_smoother_rate: 75.0 # messages/sec

# servo smoother - limits acceleration and smooths anything above limit
max_acceleration: 2.5 # meters/second^2
throttle_smoother_rate: 75.0 # messages/sec

# servo value (0 to 1) =  steering_angle_to_servo_gain * steering angle (radians) + steering_angle_to_servo_offset
steering_angle_to_servo_gain: -1.2135 # to deg = -57.2958
steering_angle_to_servo_offset: 0.5304 # to pwm = 1530
# let use PWM for servo control = 1000 to 2000,
# 1500 is the center
servo_min: 1000
servo_max: 2000
# steering angle (radians)  to PWM value
steering_angle_to_pwm_gain: 500
steering_angle_to_pwm_offset: 1500



# publish odom to base link tf
vesc_to_odom/publish_tf: true

# car wheelbase is about 25cm 
wheelbase: .35
